/* MAHJONG SOLITAIRE — pure logic (built for this codebase, not ported).

   A RACE: you (player 0) and an AI (player 1) each work an IDENTICAL shuffled
   layered tile layout. Match free pairs of identical faces to clear the board.
   First to clear wins; if both get stuck, whoever removed more tiles wins.

   The board is a stack of tiles each at integer (x, y, layer). A tile occupies a
   2x2 footprint in half-cell units (so x,y advance by 2 per "slot"), which lets the
   classic turtle/pyramid layouts half-offset upper layers. A tile is FREE when
   nothing sits on top of it AND at least one of its left/right long edges is open.

   Faces: 4 each of the 34 standard tiles (suits 1-9 x3, winds x4, dragons x3) plus
   flowers + seasons that match as wild groups. We use a compact, always-solvable
   layout generated by placing matched pairs onto free slots, so a greedy solver can
   always clear it. NO React/DOM here — deterministic given a seed. */

// ---- Tile faces -----------------------------------------------------------

export type Suit = 'bam' | 'cir' | 'cha' | 'wind' | 'drag' | 'flower' | 'season'

export interface Face {
  suit: Suit
  /** Rank within suit: 1-9 for number suits, 1-4 winds, 1-3 dragons, 1-4 flower/season index. */
  rank: number
}

export interface Tile {
  id: number
  face: Face
  /** Half-cell coordinates: a tile spans [x, x+2) x [y, y+2). */
  x: number
  y: number
  layer: number
  removed: boolean
}

/** A board is one player's copy of the layout. */
export interface Board {
  tiles: Tile[]
  /** Tile id -> index in tiles, for fast lookup. */
  byId: Record<number, number>
}

export type PlayerId = 0 | 1

export interface State {
  /** The shared layout (template) the boards were built from. */
  layout: Tile[]
  boards: [Board, Board]
  /** Per-player current selection (a tile id, or null). */
  selection: [number | null, number | null]
  winner: PlayerId | null
  /** 'race' while playing; 'over' once decided. */
  phase: 'race' | 'over'
  /** Monotonic counter incremented on every AI removal so useAITurn re-arms. */
  step: number
}

// ---- Face equality / matching --------------------------------------------

/** Two tiles match if exact face, OR both flowers, OR both seasons (wild groups). */
export function tilesMatch(a: Tile, b: Tile): boolean {
  if (a.id === b.id) return false
  const fa = a.face, fb = b.face
  if (fa.suit === 'flower' && fb.suit === 'flower') return true
  if (fa.suit === 'season' && fb.suit === 'season') return true
  return fa.suit === fb.suit && fa.rank === fb.rank
}

// ---- Geometry / free-tile model ------------------------------------------

function overlaps(ax: number, ay: number, bx: number, by: number): boolean {
  // Two 2x2 footprints overlap if they intersect in both axes.
  return ax < bx + 2 && bx < ax + 2 && ay < by + 2 && by < ay + 2
}

/** A tile is covered if any non-removed tile on the layer directly above overlaps it. */
function isCovered(board: Board, t: Tile): boolean {
  for (const o of board.tiles) {
    if (o.removed || o.id === t.id) continue
    if (o.layer === t.layer + 1 && overlaps(t.x, t.y, o.x, o.y)) return true
  }
  return false
}

/** True if a same-layer neighbour blocks the given long edge ('L' or 'R'). */
function sideBlocked(board: Board, t: Tile, side: 'L' | 'R'): boolean {
  const nx = side === 'L' ? t.x - 2 : t.x + 2
  for (const o of board.tiles) {
    if (o.removed || o.id === t.id) continue
    if (o.layer === t.layer && overlaps(nx, t.y, o.x, o.y)) return true
  }
  return false
}

/** A tile is FREE when not covered and at least one long edge (left/right) is open. */
export function isFree(board: Board, t: Tile): boolean {
  if (t.removed) return false
  if (isCovered(board, t)) return false
  return !sideBlocked(board, t, 'L') || !sideBlocked(board, t, 'R')
}

export function freeTiles(board: Board): Tile[] {
  return board.tiles.filter((t) => isFree(board, t))
}

/** All legal free matching pairs on a board (unordered, no dups). */
export function legalPairs(board: Board): Array<[Tile, Tile]> {
  const free = freeTiles(board)
  const out: Array<[Tile, Tile]> = []
  for (let i = 0; i < free.length; i++) {
    for (let j = i + 1; j < free.length; j++) {
      if (tilesMatch(free[i], free[j])) out.push([free[i], free[j]])
    }
  }
  return out
}

// ---- Board status ---------------------------------------------------------

export function tilesLeft(board: Board): number {
  let n = 0
  for (const t of board.tiles) if (!t.removed) n++
  return n
}

export function isCleared(board: Board): boolean {
  return tilesLeft(board) === 0
}

export function isStuck(board: Board): boolean {
  return !isCleared(board) && legalPairs(board).length === 0
}

/** A board is "done" (can make no further progress) when cleared or stuck. */
export function boardDone(board: Board): boolean {
  return isCleared(board) || isStuck(board)
}

// ---- Mutations ------------------------------------------------------------

function cloneBoard(b: Board): Board {
  const tiles = b.tiles.map((t) => ({ ...t }))
  const byId: Record<number, number> = {}
  tiles.forEach((t, i) => (byId[t.id] = i))
  return { tiles, byId }
}

function tileOf(board: Board, id: number): Tile {
  return board.tiles[board.byId[id]]
}

/** Remove two free matching tiles for a player; returns a new State. No-op if illegal. */
export function removePair(s: State, player: PlayerId, tileAId: number, tileBId: number): State {
  const board = s.boards[player]
  const a = tileOf(board, tileAId)
  const b = tileOf(board, tileBId)
  if (a == null || b == null) return s
  if (!isFree(board, a) || !isFree(board, b) || !tilesMatch(a, b)) return s

  const nb = cloneBoard(board)
  tileOf(nb, tileAId).removed = true
  tileOf(nb, tileBId).removed = true

  const boards: [Board, Board] = player === 0 ? [nb, s.boards[1]] : [s.boards[0], nb]
  const selection: [number | null, number | null] = [...s.selection]
  selection[player] = null
  const ns: State = { ...s, boards, selection }
  return settleWinner(ns)
}

/** Decide the winner if both boards are done (or one cleared). */
function settleWinner(s: State): State {
  const b0 = s.boards[0], b1 = s.boards[1]
  const c0 = isCleared(b0), c1 = isCleared(b1)

  // A clear wins immediately for that player (the race is "first to clear").
  if (c0 && !c1) return { ...s, winner: 0, phase: 'over' }
  if (c1 && !c0) return { ...s, winner: 1, phase: 'over' }
  if (c0 && c1) {
    // Both cleared in the same settle: player 0 (the human acting) takes it.
    return { ...s, winner: 0, phase: 'over' }
  }

  // Neither cleared: if both are done (stuck), decide by tiles removed.
  if (boardDone(b0) && boardDone(b1)) {
    const r0 = b0.tiles.length - tilesLeft(b0)
    const r1 = b1.tiles.length - tilesLeft(b1)
    const winner: PlayerId = r0 >= r1 ? 0 : 1
    return { ...s, winner, phase: 'over' }
  }
  return s
}

// ---- AI -------------------------------------------------------------------

/**
 * Greedy matcher: pick one good free pair and remove it. Heuristic — prefer a pair
 * whose removal does NOT reduce the count of remaining faces of an "endangered" face
 * to a state we can't finish; in practice we simply prefer pairs that open the most
 * new free tiles, and break ties toward flowers/seasons (wild) last so exact tiles
 * don't get stranded. Returns a new State (no-op if no pair / not racing).
 */
export function aiTurn(s: State): State {
  if (s.winner != null) return s
  const board = s.boards[1]
  const pairs = legalPairs(board)
  if (pairs.length === 0) {
    // AI can't move — settle (maybe the human already cleared, or AI is stuck).
    return settleWinner({ ...s })
  }

  // Find a winning line from the AI's current board and play its first move, so the
  // AI never strands tiles and the race comes down to speed. If no winning line
  // exists from here (shouldn't on our solvable layouts), fall back to the greedy
  // "opens-most" pick so the AI still makes progress.
  const remaining: Tile[] = board.tiles.filter((t) => !t.removed)
  const line = solveOrder(remaining)
  let pick: [number, number]
  if (line != null && line.length > 0) {
    pick = line[0]
  } else {
    let best = pairs[0]
    let bestScore = -Infinity
    for (const [a, b] of pairs) {
      const nb = cloneBoard(board)
      tileOf(nb, a.id).removed = true
      tileOf(nb, b.id).removed = true
      const opened = freeTiles(nb).length
      const wildPenalty = a.face.suit === 'flower' || a.face.suit === 'season' ? 1 : 0
      const score = opened - wildPenalty
      if (score > bestScore) {
        bestScore = score
        best = [a, b]
      }
    }
    pick = [best[0].id, best[1].id]
  }

  const ns = removePair(s, 1, pick[0], pick[1])
  return { ...ns, step: s.step + 1 }
}

// ---- Selection helper (UI convenience, pure) ------------------------------

/**
 * Player taps a tile. If it's their first selection, select it. If they tap the same
 * tile, deselect. If they have a selection and tap a matching free tile, remove the
 * pair. Otherwise switch selection to the new tile (if free). Returns new State.
 */
export function selectTile(s: State, player: PlayerId, tileId: number): State {
  if (s.winner != null) return s
  const board = s.boards[player]
  const t = tileOf(board, tileId)
  if (t == null || !isFree(board, t)) return s

  const cur = s.selection[player]
  if (cur == null) {
    const sel: [number | null, number | null] = [...s.selection]
    sel[player] = tileId
    return { ...s, selection: sel }
  }
  if (cur === tileId) {
    const sel: [number | null, number | null] = [...s.selection]
    sel[player] = null
    return { ...s, selection: sel }
  }
  const a = tileOf(board, cur)
  if (a != null && isFree(board, a) && tilesMatch(a, t)) {
    return removePair(s, player, cur, tileId)
  }
  // Switch selection.
  const sel: [number | null, number | null] = [...s.selection]
  sel[player] = tileId
  return { ...s, selection: sel }
}

// ---- Deterministic RNG ----------------------------------------------------

function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return function () {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

// ---- The deck of faces ----------------------------------------------------

/**
 * Build the standard 144-face Mahjong multiset:
 *   suits bam/cir/cha 1-9, 4 each  = 108
 *   winds 1-4, 4 each              = 16
 *   dragons 1-3, 4 each            = 12
 *   flowers 1-4, 1 each            = 4
 *   seasons 1-4, 1 each            = 4
 * Flowers/seasons are wild WITHIN their group, so they form 2 pairs each as 4 tiles.
 * Total 144 tiles = 72 pairs. We may use a SUBSET (a prefix multiset) for compact
 * layouts; faces are always emitted as matched pairs so the layout stays solvable.
 */
export function fullDeck(): Face[] {
  const faces: Face[] = []
  const push = (suit: Suit, rank: number, copies: number) => {
    for (let i = 0; i < copies; i++) faces.push({ suit, rank })
  }
  for (const suit of ['bam', 'cir', 'cha'] as Suit[]) {
    for (let r = 1; r <= 9; r++) push(suit, r, 4)
  }
  for (let r = 1; r <= 4; r++) push('wind', r, 4)
  for (let r = 1; r <= 3; r++) push('drag', r, 4)
  for (let r = 1; r <= 4; r++) push('flower', r, 1)
  for (let r = 1; r <= 4; r++) push('season', r, 1)
  return faces
}

// ---- Layout slots ---------------------------------------------------------

/**
 * A "pyramid" layout: stacked square layers, each smaller and centred over the one
 * below, so upper tiles cover the seam of four below them. Returns slot coordinates
 * (x,y,layer) in half-cell units. We pick the smallest pyramid that has >= the
 * requested number of slots, then trim to an EVEN count.
 *
 * Layer L (0-based from bottom) is a (base - 2L) x (base - 2L) grid of tiles, offset
 * by L cells (2 half-cells) on each axis to centre it.
 */
function pyramidSlots(base: number): Array<{ x: number; y: number; layer: number }> {
  const slots: Array<{ x: number; y: number; layer: number }> = []
  let layer = 0
  let side = base
  let off = 0
  while (side >= 1) {
    for (let r = 0; r < side; r++) {
      for (let c = 0; c < side; c++) {
        slots.push({ x: (off + c) * 2, y: (off + r) * 2, layer })
      }
    }
    layer++
    side -= 2
    off += 1
  }
  return slots
}

/**
 * Order slots so that we can fill them as solvable pairs: we place pairs by repeatedly
 * choosing TWO currently-free slots (covered tiles must be placed before the tiles
 * that cover them). Easiest robust approach: fill the layout TOP-DOWN by layer
 * (highest layer first) assigning faces, because removing in the reverse (bottom is
 * exposed last) — but the cleanest guarantee is the constructive pairing below.
 */

// ---- Solvable layout generation ------------------------------------------

/**
 * Generate a guaranteed-solvable filled layout.
 *
 * Strategy: simulate a SOLUTION in reverse. Start from an EMPTY board (all slots
 * "open") and repeatedly pick two slots that would be FREE on an otherwise-empty
 * board... — that's hard. Instead we use the standard trick:
 *
 *   Forward-place: maintain the set of UNFILLED slots. A slot is "placeable" now if,
 *   were the board built so far, it would be free to REMOVE LAST among remaining —
 *   equivalently we build the removal order backwards. We compute a valid REMOVAL
 *   ORDER of the empty geometry by peeling: repeatedly take any slot that is free
 *   given the not-yet-peeled slots still present. Pair consecutive peels and assign
 *   each pair a matching face. Reversing that order is a valid SOLVE order, so the
 *   resulting filled board is solvable.
 */
export function makeLayout(seed: number, pairCount: number): Tile[] {
  const rng = mulberry32(seed)

  // Choose a pyramid big enough, trim to an even slot count = 2*pairCount.
  const need = pairCount * 2
  let base = 1
  while (pyramidSlots(base).length < need) base += 1
  let slots = pyramidSlots(base)
  // Trim from the TOP layers down to exactly `need` slots, keeping a coherent shape:
  // remove the highest-layer, last-added slots first (they're the apex).
  if (slots.length > need) slots = slots.slice(0, need)

  // Build a "present" set and peel free slots to get a removal order.
  const present = slots.map((sl, i) => ({ ...sl, idx: i, removed: false }))

  function slotCovered(i: number): boolean {
    const s = present[i]
    for (const o of present) {
      if (o.removed || o.idx === i) continue
      if (o.layer === s.layer + 1 && overlaps(s.x, s.y, o.x, o.y)) return true
    }
    return false
  }
  function slotSideBlocked(i: number, side: 'L' | 'R'): boolean {
    const s = present[i]
    const nx = side === 'L' ? s.x - 2 : s.x + 2
    for (const o of present) {
      if (o.removed || o.idx === i) continue
      if (o.layer === s.layer && overlaps(nx, s.y, o.x, o.y)) return true
    }
    return false
  }
  function slotFree(i: number): boolean {
    if (present[i].removed) return false
    if (slotCovered(i)) return false
    return !slotSideBlocked(i, 'L') || !slotSideBlocked(i, 'R')
  }

  // Peel TWO simultaneously-free slots per step and pair them. Because both are free
  // in the present set BEFORE either is removed, the exact reverse is a valid solve:
  // when we add the pair back last->first, both members are free at removal time. We
  // keep them as ordered pairs so face assignment lines a matching pair onto each.
  const peelPairs: Array<[number, number]> = []
  let remaining = present.length
  let guard = present.length * 4 + 10
  while (remaining > 0 && guard-- > 0) {
    const freeIdx: number[] = []
    for (let i = 0; i < present.length; i++) if (slotFree(i)) freeIdx.push(i)
    if (freeIdx.length < 2) break // shouldn't happen for a pyramid with even slots
    // Pick two distinct currently-free slots.
    const a = freeIdx[Math.floor(rng() * freeIdx.length)]
    let b = a
    while (b === a) b = freeIdx[Math.floor(rng() * freeIdx.length)]
    present[a].removed = true
    present[b].removed = true
    peelPairs.push([a, b])
    remaining -= 2
  }
  // Any leftover slots (degenerate) get paired up; pyramids always peel cleanly.
  const leftover: number[] = []
  for (let i = 0; i < present.length; i++) if (!present[i].removed) leftover.push(i)
  for (let i = 0; i + 1 < leftover.length; i += 2) peelPairs.push([leftover[i], leftover[i + 1]])

  // Pair consecutive peels; assign matching faces from a shuffled deck of pairs.
  // Build a pool of face-pairs.
  const deck = fullDeck()
  // Group deck into matched pairs: take faces in order; flowers/seasons can pair
  // with any of their group, so just chunk each group into pairs.
  const facePairs: Array<[Face, Face]> = []
  // Bucket by group key (suit for wild groups, suit+rank for exact).
  const buckets: Record<string, Face[]> = {}
  for (const f of deck) {
    const key = f.suit === 'flower' || f.suit === 'season' ? f.suit : `${f.suit}-${f.rank}`
    ;(buckets[key] ||= []).push(f)
  }
  for (const key of Object.keys(buckets)) {
    const arr = buckets[key]
    for (let i = 0; i + 1 < arr.length; i += 2) facePairs.push([arr[i], arr[i + 1]])
  }
  // Shuffle the face-pairs deterministically.
  for (let i = facePairs.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[facePairs[i], facePairs[j]] = [facePairs[j], facePairs[i]]
  }

  // Assign one matching face-pair onto each simultaneously-free slot pair.
  const tiles: Tile[] = []
  let nextId = 0
  peelPairs.forEach(([i1, i2], k) => {
    const fp = facePairs[k % facePairs.length]
    const s1 = slots[i1]
    const s2 = slots[i2]
    tiles.push({ id: nextId++, face: { ...fp[0] }, x: s1.x, y: s1.y, layer: s1.layer, removed: false })
    tiles.push({ id: nextId++, face: { ...fp[1] }, x: s2.x, y: s2.y, layer: s2.layer, removed: false })
  })
  // Sort by id for stable ordering.
  tiles.sort((a, b) => a.id - b.id)
  return tiles
}

function buildBoard(layout: Tile[]): Board {
  const tiles = layout.map((t) => ({ ...t }))
  const byId: Record<number, number> = {}
  tiles.forEach((t, i) => (byId[t.id] = i))
  return { tiles, byId }
}

// ---- Public game constructor ----------------------------------------------

/** Default pair count for the compact pyramid (36 tiles = 18 pairs, 3 layers). */
export const DEFAULT_PAIRS = 18

export function makeGame(seed?: number): State {
  const s = seed == null ? (Math.floor(Math.random() * 0x7fffffff) | 0) : seed
  const layout = makeLayout(s, DEFAULT_PAIRS)
  return {
    layout,
    boards: [buildBoard(layout), buildBoard(layout)],
    selection: [null, null],
    winner: null,
    phase: 'race',
    step: 0,
  }
}

// ---- Solver (used by tests + as a clearability check) --------------------

/**
 * Solve a board to completion when possible. Tries a greedy "opens-most" pass first
 * (fast, clears most layouts); if that strands tiles, falls back to bounded DFS
 * backtracking which is guaranteed to find the solution for a solvable layout. Pure.
 */
export function greedySolve(layout: Tile[], seed = 1): { removed: number; cleared: boolean } {
  const order = solveOrder(layout)
  if (order != null) return { removed: layout.length, cleared: true }
  // Not fully solvable from this state — report greedy progress.
  const board = buildBoard(layout)
  let b = board
  let guard = layout.length * 4 + 10
  while (guard-- > 0) {
    const pairs = legalPairs(b)
    if (pairs.length === 0) break
    const nb = cloneBoard(b)
    nb.tiles[nb.byId[pairs[0][0].id]].removed = true
    nb.tiles[nb.byId[pairs[0][1].id]].removed = true
    b = nb
  }
  void seed
  return { removed: layout.length - tilesLeft(b), cleared: isCleared(b) }
}

/**
 * Find a full sequence of pair-removals (by tile id) that clears the layout, or null
 * if none exists. Greedy "opens-most" with DFS backtracking and a memo on the removed
 * set so it stays fast on the compact pyramid. Used by the AI to play a winning line.
 */
export function solveOrder(layout: Tile[]): Array<[number, number]> | null {
  const board = buildBoard(layout)
  const seen = new Set<string>()

  function keyOf(b: Board): string {
    let k = ''
    for (const t of b.tiles) k += t.removed ? '0' : '1'
    return k
  }

  function dfs(b: Board, acc: Array<[number, number]>): Array<[number, number]> | null {
    if (isCleared(b)) return acc
    const key = keyOf(b)
    if (seen.has(key)) return null
    seen.add(key)
    const pairs = legalPairs(b)
    if (pairs.length === 0) return null
    // Order candidates by how many tiles they open (greedy first) to find a line fast.
    const scored = pairs.map(([a, c]) => {
      const nb = cloneBoard(b)
      nb.tiles[nb.byId[a.id]].removed = true
      nb.tiles[nb.byId[c.id]].removed = true
      return { a, c, opened: freeTiles(nb).length, nb }
    })
    scored.sort((p, q) => q.opened - p.opened)
    for (const cand of scored) {
      const res = dfs(cand.nb, [...acc, [cand.a.id, cand.c.id]])
      if (res != null) return res
    }
    return null
  }

  return dfs(board, [])
}
