/* CATHEDRAL — pure logic (no React/DOM).
   A 2-player territory/polyomino game on a 10x10 board. One neutral CATHEDRAL hexomino is
   placed first; then players alternate placing one of their building polyominoes onto empty
   cells. When a placement, together with that player's own pieces and the board edges, fully
   ENCLOSES an empty region, the player claims it: if the region holds AT MOST ONE opponent
   building and NO neutral cathedral, that single opponent building (if any) is removed and
   returned to its owner, and every empty cell of the region is marked as the claimer's
   territory (only they may build there afterward). The game ends when neither player can
   place a piece; the winner is whoever has the FEWEST leftover (unplaced) squares.

   Pieces may ROTATE but NOT flip — orientations are generated by 90° rotations only and
   deduped. Players share an identical fixed set of ~12 building pieces.

   Falsy-zero care: players are 0 | 1, coordinates and indices include 0, leftover counts can
   be 0. We never truthiness-test those — compare players with === and treat empty cells as
   null with == null / != null checks. */

export type Player = 0 | 1
// A board cell: null (empty/unclaimed), 'cath' (neutral cathedral),
// 0 / 1 = a building owned by that player, 't0' / 't1' = claimed-empty territory marker.
export type Cell = null | 'cath' | Player | 't0' | 't1'

export interface PieceDef {
  id: string
  name: string
  /** Base shape as [row, col] offsets (normalized to start at 0,0). */
  cells: [number, number][]
  /** Cell count (squares occupied). */
  size: number
}

export interface CathedralState {
  board: Cell[]            // N*N row-major
  /** Remaining (unplaced) piece ids per player. */
  remaining: [string[], string[]]
  turn: Player
  winner: Player | 'tie' | null
  /** A monotonically increasing counter — bump on every action so AI drivers re-arm. */
  step: number
  log: { t: 'you' | 'ai' | 'sys'; x: string }[]
}

export const N = 10

// ----- Piece set -------------------------------------------------------------
// Standard Cathedral-style building set: a fixed roster shared by both players.
// Shapes are lists of [dr, dc] offsets. NOT flippable — only rotations are used.
export const PIECES: PieceDef[] = mkPieces([
  ['tavern', 'Tavern', [[0, 0]]],                               // 1
  ['stable', 'Stable', [[0, 0], [0, 1]]],                       // 2
  ['inn', 'Inn', [[0, 0], [0, 1], [1, 1]]],                     // 3  L-tromino
  ['bridge', 'Bridge', [[0, 0], [0, 1], [0, 2]]],               // 3  I-tromino
  ['square', 'Square', [[0, 0], [0, 1], [1, 0], [1, 1]]],       // 4  O
  ['manor', 'Manor', [[0, 0], [0, 1], [0, 2], [1, 1]]],         // 4  T-tetromino
  ['abbey', 'Abbey', [[0, 0], [0, 1], [1, 1], [1, 2]]],         // 4  S-tetromino
  ['tower', 'Tower', [[0, 0], [1, 0], [1, 1], [2, 1]]],         // 4  Z-tetromino
  ['academy', 'Academy', [[0, 0], [1, 0], [2, 0], [2, 1]]],     // 4  L-tetromino
  ['infirmary', 'Infirmary', [[0, 1], [1, 0], [1, 1], [1, 2]]], // 4  T-up (distinct)
  ['castle', 'Castle', [[0, 0], [0, 1], [0, 2], [1, 0], [1, 2]]], // 5  U-pentomino
  ['cathedral_keep', 'Keep', [[0, 0], [0, 1], [0, 2], [1, 1], [2, 1]]], // 5  T-pentomino
])

// The single neutral cathedral piece — a 6-cell hexomino (cross-like).
export const CATHEDRAL: PieceDef = mkPiece('cathedral', 'Cathedral', [
  [0, 1], [1, 0], [1, 1], [1, 2], [2, 1], [3, 1],
])

function mkPiece(id: string, name: string, cells: [number, number][]): PieceDef {
  const norm = normalize(cells)
  return { id, name, cells: norm, size: norm.length }
}
function mkPieces(defs: [string, string, [number, number][]][]): PieceDef[] {
  return defs.map(([id, name, cells]) => mkPiece(id, name, cells))
}

export const PIECE_BY_ID: Record<string, PieceDef> = Object.fromEntries(
  [...PIECES, CATHEDRAL].map((p) => [p.id, p]),
)

// ----- Orientations ----------------------------------------------------------
function normalize(cells: [number, number][]): [number, number][] {
  const minR = Math.min(...cells.map((c) => c[0]))
  const minC = Math.min(...cells.map((c) => c[1]))
  return cells
    .map((c) => [c[0] - minR, c[1] - minC] as [number, number])
    .sort((a, b) => a[0] - b[0] || a[1] - b[1])
}

function sig(cells: [number, number][]): string {
  return cells.map((c) => c[0] + ':' + c[1]).join(';')
}

/** All unique 90°-rotation orientations of a piece (no flips), normalized + deduped. */
export function orientations(id: string): [number, number][][] {
  const base = PIECE_BY_ID[id].cells
  const out: [number, number][][] = []
  const seen = new Set<string>()
  let cur = base.map((c) => [c[0], c[1]] as [number, number])
  for (let r = 0; r < 4; r++) {
    const norm = normalize(cur)
    const s = sig(norm)
    if (!seen.has(s)) {
      seen.add(s)
      out.push(norm)
    }
    cur = cur.map((c) => [c[1], -c[0]] as [number, number]) // rotate 90° CW
  }
  return out
}

// ----- Board helpers ---------------------------------------------------------
export const idx = (r: number, c: number): number => r * N + c
export const inBounds = (r: number, c: number): boolean => r >= 0 && r < N && c >= 0 && c < N

/** territory marker for a player ('t0' | 't1'). */
const terr = (p: Player): 't0' | 't1' => (p === 0 ? 't0' : 't1')

/** Can player `p` build on this cell? Empty (null) always; their own territory marker yes. */
function buildable(cell: Cell, p: Player): boolean {
  if (cell == null) return true
  if (cell === terr(p)) return true
  return false
}

export function makeGame(): CathedralState {
  const board: Cell[] = new Array(N * N).fill(null)
  // Pre-place the neutral cathedral near the centre, fixed orientation.
  const ori = CATHEDRAL.cells
  const r0 = 3
  const c0 = 4
  for (const [dr, dc] of ori) board[idx(r0 + dr, c0 + dc)] = 'cath'
  return {
    board,
    remaining: [PIECES.map((p) => p.id), PIECES.map((p) => p.id)],
    turn: 0,
    winner: null,
    step: 0,
    log: [{ t: 'sys', x: 'The cathedral is consecrated at the heart of the field.' }],
  }
}

// ----- Placement enumeration -------------------------------------------------
export interface Placement {
  pieceId: string
  ori: number
  /** Absolute board cell indices the piece would occupy. */
  cells: number[]
  anchor: [number, number]
}

/** True if the given absolute cells form a legal placement for player p. */
function fits(board: Cell[], p: Player, cells: number[]): boolean {
  for (const i of cells) {
    if (i < 0 || i >= N * N) return false
    if (!buildable(board[i], p)) return false
  }
  return true
}

/** All legal placements of all remaining pieces for player p. */
export function legalPlacements(s: CathedralState, p: Player): Placement[] {
  const out: Placement[] = []
  for (const id of s.remaining[p]) {
    const oris = orientations(id)
    for (let o = 0; o < oris.length; o++) {
      const shape = oris[o]
      const maxR = Math.max(...shape.map((c) => c[0]))
      const maxC = Math.max(...shape.map((c) => c[1]))
      for (let r = 0; r + maxR < N; r++) {
        for (let c = 0; c + maxC < N; c++) {
          const cells = shape.map(([dr, dc]) => idx(r + dr, c + dc))
          if (fits(s.board, p, cells)) {
            out.push({ pieceId: id, ori: o, cells, anchor: [r, c] })
          }
        }
      }
    }
  }
  return out
}

/** Legal placements for a single piece id (used by the UI for hover/select). */
export function placementsForPiece(s: CathedralState, p: Player, id: string): Placement[] {
  const out: Placement[] = []
  const oris = orientations(id)
  for (let o = 0; o < oris.length; o++) {
    const shape = oris[o]
    const maxR = Math.max(...shape.map((c) => c[0]))
    const maxC = Math.max(...shape.map((c) => c[1]))
    for (let r = 0; r + maxR < N; r++) {
      for (let c = 0; c + maxC < N; c++) {
        const cells = shape.map(([dr, dc]) => idx(r + dr, c + dc))
        if (fits(s.board, p, cells)) out.push({ pieceId: id, ori: o, cells, anchor: [r, c] })
      }
    }
  }
  return out
}

export function canPlaceAny(s: CathedralState, p: Player): boolean {
  for (const id of s.remaining[p]) {
    if (placementsForPiece(s, p, id).length > 0) return true
  }
  return false
}

// ----- Enclosure detection ---------------------------------------------------
// After player p places, scan empty (and opponent-territory? no — only unowned-empty)
// regions reachable by 4-connectivity that do NOT touch a board edge and are bounded only
// by p's own buildings/territory (and the edges). Such a fully-enclosed region is captured
// IF it contains at most one opponent building and no neutral cathedral.
//
// We flood-fill over cells that are "interior to p's wall": a region is the set of cells
// that are NOT p's own building, reachable from a seed without crossing one of p's buildings
// or its own territory marker. A region is "enclosed by p" when it never reaches the board
// edge. Inside such a region we count opponent buildings and cathedral cells.

interface Region {
  cells: number[]        // all non-(p-building) cells in the region
  emptyCells: number[]   // null or p-territory cells (claimable space)
  touchesEdge: boolean
  oppBuildings: Set<number> // distinct opponent building "ids" — but buildings have no ids on
                            // the board; we approximate by connected opponent groups.
  oppCells: number[]
  hasCath: boolean
}

/** Wall cells for player p are p's own buildings AND p's own territory markers. */
function isWall(cell: Cell, p: Player): boolean {
  if (cell === p) return true
  if (cell === terr(p)) return true
  return false
}

function floodRegions(board: Cell[], p: Player): Region[] {
  const seen = new Uint8Array(N * N)
  const regions: Region[] = []
  for (let start = 0; start < N * N; start++) {
    if (seen[start]) continue
    if (isWall(board[start], p)) continue
    // BFS the maximal region of non-wall cells.
    const queue = [start]
    seen[start] = 1
    const region: Region = {
      cells: [],
      emptyCells: [],
      touchesEdge: false,
      oppBuildings: new Set(),
      oppCells: [],
      hasCath: false,
    }
    while (queue.length) {
      const cur = queue.pop()!
      const r = Math.floor(cur / N)
      const c = cur % N
      region.cells.push(cur)
      const cell = board[cur]
      if (cell == null || cell === terr(p)) region.emptyCells.push(cur)
      else if (cell === 'cath') region.hasCath = true
      else if (cell === (1 - p) || cell === terr((1 - p) as Player)) region.oppCells.push(cur)
      if (r === 0 || r === N - 1 || c === 0 || c === N - 1) region.touchesEdge = true
      const nbrs = [
        r > 0 ? cur - N : -1,
        r < N - 1 ? cur + N : -1,
        c > 0 ? cur - 1 : -1,
        c < N - 1 ? cur + 1 : -1,
      ]
      for (const nb of nbrs) {
        if (nb < 0 || seen[nb]) continue
        if (isWall(board[nb], p)) continue
        seen[nb] = 1
        queue.push(nb)
      }
    }
    regions.push(region)
  }
  return regions
}

/** Count connected opponent BUILDING groups within a region's opponent cells. */
function countOppGroups(board: Cell[], oppCells: number[], p: Player): number {
  const set = new Set(oppCells.filter((i) => board[i] === (1 - p)))
  const visited = new Set<number>()
  let groups = 0
  for (const start of set) {
    if (visited.has(start)) continue
    groups++
    const q = [start]
    visited.add(start)
    while (q.length) {
      const cur = q.pop()!
      const r = Math.floor(cur / N)
      const c = cur % N
      const nbrs = [
        r > 0 ? cur - N : -1,
        r < N - 1 ? cur + N : -1,
        c > 0 ? cur - 1 : -1,
        c < N - 1 ? cur + 1 : -1,
      ]
      for (const nb of nbrs) {
        if (nb < 0 || !set.has(nb) || visited.has(nb)) continue
        visited.add(nb)
        q.push(nb)
      }
    }
  }
  return groups
}

export interface CaptureResult {
  board: Cell[]
  claimedCells: number[]
  removedOppCells: number[]
  removedPieceCount: number
}

/** Resolve all enclosures owned by p on the board, mutating into a fresh board. */
export function resolveCaptures(board: Cell[], p: Player): CaptureResult {
  const next = board.slice()
  const regions = floodRegions(board, p)
  const claimedCells: number[] = []
  const removedOppCells: number[] = []
  let removedPieceCount = 0
  for (const region of regions) {
    if (region.touchesEdge) continue
    if (region.hasCath) continue
    const oppGroups = countOppGroups(board, region.oppCells, p)
    if (oppGroups > 1) continue
    // Capture: remove the (at most one) opponent building, claim all empty cells.
    if (oppGroups === 1) {
      for (const i of region.oppCells) {
        if (board[i] === (1 - p)) {
          next[i] = terr(p)
          removedOppCells.push(i)
        }
      }
      removedPieceCount += 1
    }
    for (const i of region.emptyCells) {
      if (next[i] == null || next[i] === terr(p)) {
        next[i] = terr(p)
        claimedCells.push(i)
      }
    }
  }
  return { board: next, claimedCells, removedOppCells, removedPieceCount }
}

// ----- Placing ---------------------------------------------------------------
/** Place piece `pieceId` for player p occupying absolute `cells`. Returns next state
    (unchanged if illegal). Handles enclosure detection + capture, then passes the turn. */
export function place(s: CathedralState, p: Player, pieceId: string, cells: number[]): CathedralState {
  if (s.winner != null) return s
  if (s.turn !== p) return s
  if (!s.remaining[p].includes(pieceId)) return s
  if (!fits(s.board, p, cells)) return s
  // sanity: cells must match some orientation of the piece (size check is a cheap guard).
  const def = PIECE_BY_ID[pieceId]
  if (!def || cells.length !== def.size) return s

  const board = s.board.slice()
  for (const i of cells) board[i] = p

  const cap = resolveCaptures(board, p)
  const remaining: [string[], string[]] = [s.remaining[0].slice(), s.remaining[1].slice()]
  // remove the placed piece
  remaining[p] = remaining[p].filter((id) => id !== pieceId)
  // return captured opponent buildings (one piece worth) — restore one removed piece to owner.
  // We can't know exactly WHICH opponent piece id was on those cells (board stores no ids),
  // so we return the smallest-equivalent: give the opponent back a piece they had placed.
  // To keep the model honest we approximate by returning a piece of matching cell-count.
  const opp = (1 - p) as Player
  if (cap.removedPieceCount > 0) {
    returnCapturedPiece(remaining, opp, cap.removedOppCells.length)
  }

  const who: 'you' | 'ai' = p === 0 ? 'you' : 'ai'
  const log = s.log.slice()
  log.push({ t: who, x: `${who === 'you' ? 'You' : 'The rival'} raised the ${def.name}.` })
  if (cap.claimedCells.length > 0) {
    log.push({
      t: who,
      x: `Territory enclosed — ${cap.claimedCells.length} square${cap.claimedCells.length === 1 ? '' : 's'} claimed${cap.removedPieceCount > 0 ? ', a rival building razed' : ''}.`,
    })
  }

  let next: CathedralState = {
    board: cap.board,
    remaining,
    turn: opp,
    winner: null,
    step: s.step + 1,
    log,
  }
  next = settleTurn(next)
  return next
}

/** When a capture removes an opponent building, return one piece to that player's hand.
    Pick the largest remaining-piece-absent id of matching size if possible, else any small
    piece id that is currently NOT in hand (i.e. was placed). Best-effort restock. */
function returnCapturedPiece(remaining: [string[], string[]], owner: Player, size: number): void {
  const inHand = new Set(remaining[owner])
  // ids the owner has already placed (not in hand), preferring matching size.
  const placed = PIECES.filter((pc) => !inHand.has(pc.id))
  if (placed.length === 0) return
  const bySize = placed.find((pc) => pc.size === size) || placed[0]
  remaining[owner] = [...remaining[owner], bySize.id]
}

/** If the player to move can't place, pass; if neither can, end the game. */
function settleTurn(s: CathedralState): CathedralState {
  let cur: CathedralState = s
  let safety = 0
  while (cur.winner == null && safety++ < 4) {
    if (canPlaceAny(cur, cur.turn)) return cur
    const other = (1 - cur.turn) as Player
    if (!canPlaceAny(cur, other)) {
      return Object.assign({}, cur, { winner: decideWinner(cur) })
    }
    // current player passes
    const log = cur.log.slice()
    log.push({ t: 'sys', x: `${cur.turn === 0 ? 'You have' : 'The rival has'} no legal move — passing.` })
    cur = Object.assign({}, cur, { turn: other, step: cur.step + 1, log })
  }
  return cur
}

/** Leftover (unplaced) squares for player p. */
export function leftoverSquares(s: CathedralState, p: Player): number {
  let total = 0
  for (const id of s.remaining[p]) total += PIECE_BY_ID[id].size
  return total
}

export function placedSquares(s: CathedralState, p: Player): number {
  const allp = PIECES.reduce((a, pc) => a + pc.size, 0)
  return allp - leftoverSquares(s, p)
}

/** Winner = fewest leftover squares (most placed). Ties broken to 'tie'. */
export function decideWinner(s: CathedralState): Player | 'tie' {
  const a = leftoverSquares(s, 0)
  const b = leftoverSquares(s, 1)
  if (a < b) return 0
  if (b < a) return 1
  return 'tie'
}

// ----- AI --------------------------------------------------------------------
/** Greedy AI: among legal placements, prefer ones that capture opponent buildings, then
    ones that claim the most territory, then placing the largest piece (reduce leftover),
    with a light center/own-clustering tiebreak. Search is capped for speed. */
export function aiTurn(s: CathedralState): CathedralState {
  if (s.winner != null || s.turn !== 1) return s
  const p: Player = 1
  const placements = legalPlacements(s, p)
  if (placements.length === 0) {
    // can't place — settle (pass / end)
    return settleTurn(Object.assign({}, s, { step: s.step + 1 }))
  }

  // Cap the number of placements scored for speed.
  const CAP = 700
  const pool = placements.length > CAP ? sampleEvenly(placements, CAP) : placements

  let best: Placement | null = null
  let bestScore = -Infinity
  for (const pl of pool) {
    const def = PIECE_BY_ID[pl.pieceId]
    const board = s.board.slice()
    for (const i of pl.cells) board[i] = p
    const cap = resolveCaptures(board, p)
    let score = 0
    score += cap.removedPieceCount * 1000   // capturing a rival building is huge
    score += cap.claimedCells.length * 8     // claimed territory
    score += def.size * 3                     // place big pieces → fewer leftovers
    score += centerBias(pl.cells)             // small positional nudge
    if (score > bestScore) {
      bestScore = score
      best = pl
    }
  }
  if (!best) best = pool[0]
  return place(s, p, best.pieceId, best.cells)
}

function centerBias(cells: number[]): number {
  // prefer placements nearer the centre (more enclosing potential), tiny weight.
  let bias = 0
  for (const i of cells) {
    const r = Math.floor(i / N)
    const c = i % N
    bias -= (Math.abs(r - 4.5) + Math.abs(c - 4.5)) * 0.05
  }
  return bias
}

function sampleEvenly<T>(arr: T[], k: number): T[] {
  const out: T[] = []
  const stride = arr.length / k
  for (let i = 0; i < k; i++) out.push(arr[Math.floor(i * stride)])
  return out
}
