import { defineConfig } from 'vite'
import { resolve } from 'node:path'
import react from '@vitejs/plugin-react'

// Multi-page app: the library is the root entry, and every playable game is its own
// self-contained HTML entry under games/. This mirrors the design handoff's "one
// self-contained page per game" model and keeps each game's global CSS isolated
// (the library and each game reuse class names like .app / .masthead / .modal).
// Adding a game = drop a games/<id>.html entry + a src/games/<id>/ folder, then
// register it in src/data/playable.ts.
//
// `base: './'` makes asset URLs relative so the built site also works from a subpath
// (e.g. a GitHub Pages project site) or straight off the filesystem.
export default defineConfig({
  base: './',
  plugins: [react()],
  build: {
    rollupOptions: {
      input: {
        library: resolve(__dirname, 'index.html'),
        yahtzee: resolve(__dirname, 'games/yahtzee.html'),
        xiangqi: resolve(__dirname, 'games/xiangqi.html'),
        skull_king: resolve(__dirname, 'games/skull_king.html'),
        the_crew: resolve(__dirname, 'games/the_crew.html'),
        yinsh: resolve(__dirname, 'games/yinsh.html'),
        tiny_towns: resolve(__dirname, 'games/tiny_towns.html'),
        tictactoe: resolve(__dirname, 'games/tictactoe.html'),
        connect_four: resolve(__dirname, 'games/connect_four.html'),
        reversi: resolve(__dirname, 'games/reversi.html'),
        checkers: resolve(__dirname, 'games/checkers.html'),
        gomoku: resolve(__dirname, 'games/gomoku.html'),
        nim: resolve(__dirname, 'games/nim.html'),
        dots_boxes: resolve(__dirname, 'games/dots_boxes.html'),
        blackjack: resolve(__dirname, 'games/blackjack.html'),
        mancala: resolve(__dirname, 'games/mancala.html'),
        breakthrough: resolve(__dirname, 'games/breakthrough.html'),
        pig: resolve(__dirname, 'games/pig.html'),
        mastermind: resolve(__dirname, 'games/mastermind.html'),
        battleship: resolve(__dirname, 'games/battleship.html'),
        onitama: resolve(__dirname, 'games/onitama.html'),
        hex: resolve(__dirname, 'games/hex.html'),
        quoridor: resolve(__dirname, 'games/quoridor.html'),
        quarto: resolve(__dirname, 'games/quarto.html'),
        pentago: resolve(__dirname, 'games/pentago.html'),
        morris: resolve(__dirname, 'games/morris.html'),
        ataxx: resolve(__dirname, 'games/ataxx.html'),
        konane: resolve(__dirname, 'games/konane.html'),
        pong_hau_ki: resolve(__dirname, 'games/pong_hau_ki.html'),
        fox_hounds: resolve(__dirname, 'games/fox_hounds.html'),
        amazons: resolve(__dirname, 'games/amazons.html'),
        lines_of_action: resolve(__dirname, 'games/lines_of_action.html'),
        santorini: resolve(__dirname, 'games/santorini.html'),
        tablut: resolve(__dirname, 'games/tablut.html'),
        surakarta: resolve(__dirname, 'games/surakarta.html'),
        yote: resolve(__dirname, 'games/yote.html'),
        sudoku: resolve(__dirname, 'games/sudoku.html'),
        minesweeper: resolve(__dirname, 'games/minesweeper.html'),
        abalone: resolve(__dirname, 'games/abalone.html'),
        fanorona: resolve(__dirname, 'games/fanorona.html'),
        alquerque: resolve(__dirname, 'games/alquerque.html'),
        dara: resolve(__dirname, 'games/dara.html'),
        pente: resolve(__dirname, 'games/pente.html'),
        kamisado: resolve(__dirname, 'games/kamisado.html'),
        tsuro: resolve(__dirname, 'games/tsuro.html'),
        liars_dice: resolve(__dirname, 'games/liars_dice.html'),
        backgammon: resolve(__dirname, 'games/backgammon.html'),
        love_letter: resolve(__dirname, 'games/love_letter.html'),
        no_thanks: resolve(__dirname, 'games/no_thanks.html'),
        zombie_dice: resolve(__dirname, 'games/zombie_dice.html'),
        ur: resolve(__dirname, 'games/ur.html'),
        shut_the_box: resolve(__dirname, 'games/shut_the_box.html'),
        coloretto: resolve(__dirname, 'games/coloretto.html'),
        entropy: resolve(__dirname, 'games/entropy.html'),
        lost_cities: resolve(__dirname, 'games/lost_cities.html'),
        jaipur: resolve(__dirname, 'games/jaipur.html'),
        fox_in_forest: resolve(__dirname, 'games/fox_in_forest.html'),
        qwixx: resolve(__dirname, 'games/qwixx.html'),
        cant_stop: resolve(__dirname, 'games/cant_stop.html'),
        carnac: resolve(__dirname, 'games/carnac.html'),
        dominoes: resolve(__dirname, 'games/dominoes.html'),
        quixo: resolve(__dirname, 'games/quixo.html'),
        kalah: resolve(__dirname, 'games/kalah.html'),
        tafl: resolve(__dirname, 'games/tafl.html'),
        hearts: resolve(__dirname, 'games/hearts.html'),
        spades: resolve(__dirname, 'games/spades.html'),
        gin_rummy: resolve(__dirname, 'games/gin_rummy.html'),
        cribbage: resolve(__dirname, 'games/cribbage.html'),
        skull: resolve(__dirname, 'games/skull.html'),
        sushi_go: resolve(__dirname, 'games/sushi_go.html'),
        parade: resolve(__dirname, 'games/parade.html'),
        euchre: resolve(__dirname, 'games/euchre.html'),
        wari: resolve(__dirname, 'games/wari.html'),
        mijnlieff: resolve(__dirname, 'games/mijnlieff.html'),
        hanamikoji: resolve(__dirname, 'games/hanamikoji.html'),
        coup: resolve(__dirname, 'games/coup.html'),
        point_salad: resolve(__dirname, 'games/point_salad.html'),
        azul: resolve(__dirname, 'games/azul.html'),
        kingdomino: resolve(__dirname, 'games/kingdomino.html'),
        qwirkle: resolve(__dirname, 'games/qwirkle.html'),
        splendor: resolve(__dirname, 'games/splendor.html'),
        pickomino: resolve(__dirname, 'games/pickomino.html'),
        cockroach_poker: resolve(__dirname, 'games/cockroach_poker.html'),
        battle_line: resolve(__dirname, 'games/battle_line.html'),
        port_royal: resolve(__dirname, 'games/port_royal.html'),
        patchwork: resolve(__dirname, 'games/patchwork.html'),
        cartographers: resolve(__dirname, 'games/cartographers.html'),
        welcome_to: resolve(__dirname, 'games/welcome_to.html'),
        thats_pretty_clever: resolve(__dirname, 'games/thats_pretty_clever.html'),
        star_realms: resolve(__dirname, 'games/star_realms.html'),
        machi_koro: resolve(__dirname, 'games/machi_koro.html'),
        cascadia: resolve(__dirname, 'games/cascadia.html'),
        king_of_tokyo: resolve(__dirname, 'games/king_of_tokyo.html'),
        chinese_checkers: resolve(__dirname, 'games/chinese_checkers.html'),
        sequence: resolve(__dirname, 'games/sequence.html'),
        sagrada: resolve(__dirname, 'games/sagrada.html'),
        ingenious: resolve(__dirname, 'games/ingenious.html'),
        carcassonne: resolve(__dirname, 'games/carcassonne.html'),
        twixt: resolve(__dirname, 'games/twixt.html'),
        air_land_sea: resolve(__dirname, 'games/air_land_sea.html'),
        jotto: resolve(__dirname, 'games/jotto.html'),
        deep_sea_adventure: resolve(__dirname, 'games/deep_sea_adventure.html'),
        blokus_duo: resolve(__dirname, 'games/blokus_duo.html'),
        cathedral: resolve(__dirname, 'games/cathedral.html'),
        blockade: resolve(__dirname, 'games/blockade.html'),
        tak: resolve(__dirname, 'games/tak.html'),
        shobu: resolve(__dirname, 'games/shobu.html'),
        trax: resolve(__dirname, 'games/trax.html'),
        hive: resolve(__dirname, 'games/hive.html'),
        ludo: resolve(__dirname, 'games/ludo.html'),
      },
    },
  },
})
